lib/engine/RequestDefinition.js
package.json
test/unit/engine/RequestDefinition.js

The GET requests automatically recognize
type of request (list or entity or stream).
The patch change priority of checks. List
has greatest priority now.
Topic: #2

[FIX] Change request type recognition

---

lib/agent/Agent.js
lib/agent/batch/Request.js
lib/engine/FunctionImport.js
lib/engine/QueryableResource.js
lib/engine/RequestDefinition.js
test/unit/agent/Agent.js
test/unit/agent/batch/Request.js
test/unit/engine/FunctionImport.js
test/unit/engine/QueryableResource.js
test/unit/engine/RequestDefinition.js

Some services does not support CSRF token handling. The patch enables usage of the services by odata-library.

Read content for services without CSRF token support

---

doc/GET_ENTITY_SET.md
lib/engine/RequestDefinition.js
test/unit/engine/RequestDefinition.js

Read correctly stream from entity set by definition of single entity.  The previous implementation accepts only 1:1 navigation properties.

Read stream by single entity

---

lib/engine/NavigationProperty.js
lib/engine/QueryableResource.js
lib/engine/Resource.js
test/unit/engine/NavigationProperty.js
test/unit/engine/QueryableResource.js
test/unit/engine/Resource.js

Many methods of the [Resource](https://github.com/SAP/odata-library/blob/master/lib/engine/Resource.js) class (and its derived classes) should return `this` context for the methods chaining but actually return [request](https://github.com/SAP/odata-library/blob/master/lib/engine/RequestDefinition.js) context instead.
For example this sample would not work:
```javascript
service.C_AllocationCycleTP
.queryParameter("$format", "json")
.queryParameter("$top", "10")
.get();
```
source: https://github.com/SAP/odata-library/blob/master/doc/GET_ENTITY_SET.md#use-queryparameter
as after the first `queryParameter(...)` call the actual context is `this.defaultRequest` which does not contain the `queryParameter` method and would cause failure.
This PR fixes the return values of similar methods to …

[FIX] Return correct context for chaining

---

gulpfile.js
lib/engine/NavigationProperty.js
lib/model/EdmxModel.js
lib/model/oasis/CsdlSchema.js
lib/model/oasis/schema/Action.js
lib/model/oasis/schema/EntityType.js
lib/model/oasis/schema/Function.js
test/unit/engine/NavigationProperty.js
test/unit/model/oasis/CsdlSchemaNoDependencies.js
test/unit/model/oasis/schema/Action.js
test/unit/model/oasis/schema/EntityType.js
test/unit/model/oasis/schema/EntityTypeNoDependencies.js
test/unit/model/oasis/schema/Function.js

Share one Entity(Complex) type definition by more EntityTypes. 
Correctly process Action/FunctionImport type definition with namespace
Cleans request definition for NavigationProperty "parent" EntitySet.

Use BaseType attribute to define EntityType key

---

CHANGELOG.md
lib/engine/NavigationProperty.js
lib/engine/QueryableResource.js
package.json
test/unit/engine/NavigationProperty.js
test/unit/engine/QueryableResource.js

The ccf6f0e5819fa5d8d4c4c9d17d55666b2bb8f404
causes regression with navigation property
handling

[FIX] Key has to return request instance

---

lib/model/nw/extensions/sap/EntityTypeExtender.js
lib/model/nw/extensions/sap/common/SideEffectsType.js
package.json
test/unit/model/nw/extensions/sap/EntityTypeExtender.js
test/unit/model/nw/extensions/sap/common/SideEffectsType.js

Annotations could define property as path with
link to property from navigation property property
instead of link to own property. The patch implements
finding of the property in navigation property.
Topic: #20

[FIX] Parse PropertyPath with Navigation Property

---

CHANGELOG.md
doc/ACTIVE_OPERATIONS.md
lib/agent/Agent.js
lib/agent/batch/Batch.js
lib/engine/QueryableResource.js
test/unit/agent/Agent.js
test/unit/agent/batch/Batch.js
test/unit/engine/QueryableResource.js

Implements possibility to use "PATCH" method
via QueryableResource.patch to update entities
for servers which implements OData protocol
version 3.0 and newer. There is no formal check
for OData protocol version.  Usage of patch for older
version of OData protocol is possible.
Topic: #19

[FEATURE] PUT method for OData 3.0 and newer

---

lib/agent/batch/Response.js
test/unit/agent/batch/Response.js

Resolves responses from batch (inside batch) as
instance of Error class instead of rejects them.
It follows browser behavior. The real HTTP request
(whole batch) returns 202 status code even if
responses inside batch has error status code (
greather than 400)
Topic: #26

[FEATURE] Resolves batch responses with errors

---

CHANGELOG.md
lib/agent/url.js
package.json
test/unit/agent/url.js

Additional slash has been historically used,
but It causes probles with some OData servers
Whis is not able to correctly process the url
with double slash.
Topic: #33

[FIX] Remove additional slash from base url

---

lib/engine/FunctionImport.js
lib/engine/QueryableResource.js
package.json
test/unit/engine/FunctionImport.js
test/unit/engine/QueryableResource.js

Reset of the defaultRequest object is called
before the network request if called (not after)
to prevent race condition bug with multiple
calls in one tick.
Topic: #35

[FIX] Finish request definition inside tick

---

LICENSE

In order to be able to identify the main license of all managed repositories centrally, the SAP Open Source Program Office (OSPO) asks all teams to have an identifiable license in their repositories. While you are properly using the [REUSE tool](https://reuse.software) (thanks for that!), a license file that specifies the main license of your project is missing. As a consequence, the [license of this repository is not detected properly by GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#detecting-a-license). This PR includes text from a [GitHub license template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that should …

[INTERNAL] Chore: Use GitHub license template

---

README.md

In line with SAP OSPO requirements, this PR adds the REUSE Tool links to the README
**Notes:** 
- Please register the repository with the REUSE Tool to complete the integration (see #45 and #46)
- The .npm* files don't seem to be mentioned in the dep5 file. Please have a look and change the REUSE tool metadata accordingly there. Thanks!
Fixes #44

[INTERNAL] Add REUSE tool information to README

---

lib/model/aggregate.js
lib/model/nw/schema/ComplexType.js
lib/model/oasis/schema/ComplexType.js
lib/model/schema/ComplexType.js
test/unit/model/aggregate.js
test/unit/model/schema/ComplexType.js

Implement formatBody functions for ComplexTypes.
formatBody recursively formats properties in
POST/PUT/MERGE requests.
Topic: #54

[FIX] Correctly create entity with complex type

---

lib/agent/Agent.js
lib/agent/batch/Batch.js
lib/agent/batch/Request.js
lib/agent/batch/Response.js
lib/agent/parsers.js
lib/engine/QueryableResource.js
lib/engine/RequestDefinition.js
lib/engine/responseType.js
package.json
test/unit/agent/Agent.js
test/unit/agent/batch/Batch.js
test/unit/agent/batch/Request.js
test/unit/agent/batch/Response.js
test/unit/agent/parsers.js
test/unit/engine/QueryableResource.js
test/unit/engine/RequestDefinition.js
test/unit/engine/responseType.js

Count had separated implementation to generate
HTTP requests.  The patch uses executeGet method
to run count request instead of separated code.
Topic: #62

[FEATURE] Add $filter to entity set count request

---

CHANGELOG.md
lib/engine/QueryableResource.js
lib/model/nw/CsdlSchema.js
lib/model/nw/schema/ComplexType.js
lib/model/nw/schema/EntityType.js
lib/model/oasis/annotations/AnnotationTarget.js
lib/model/oasis/schema/ComplexType.js
package.json
test/unit/engine/QueryableResource.js
test/unit/model/nw/CsdlSchema.js
test/unit/model/nw/schema/ComplexType.js
test/unit/model/nw/schema/EntityType.js
test/unit/model/oasis/annotations/AnnotationTarget.js

Add possibility to resolve properties from EntityType in metadata which is defined by path to NavigationProperty. The patch resolves the issue  #66

Resolve properties from navigation properties

---

CHANGELOG.md
lib/engine/QueryableResource.js
package.json
test/unit/engine/QueryableResource.js

Fix regression when 1:1 navigation property
properties has moved to main entity during
body convertion. I have removed hashes from 
change log for inaccuracy.
Topic: #65

[FIX] Correctly process 1:1 navigation property

---

lib/engine/QueryableResource.js
lib/model/nw/schema/EntityType.js
lib/model/nw/schema/NavigationProperty.js
lib/model/oasis/schema/EdmSimpleType.js
test/unit/engine/QueryableResource.js
test/unit/model/nw/schema/EntityType.js
test/unit/model/nw/schema/NavigationProperty.js
test/unit/model/oasis/schema/EdmSimpleType.js

Create entities by navigation properties ("deep
insert") was not implemented for v4. The patch
unified API for v4 & v2 metadata NavigationProperty
classes.
Topic: #68

[FEATURE] Send navigation properties for v4

---

doc/INITIALIZE.md
lib/agent/authentication.js
lib/agent/authentication/cookie.js
lib/agent/settings.js
test/unit/agent/authentication.js
test/unit/agent/authentication/cookie.js
test/unit/agent/settings.js

Add possibility to specify authentication type directly without automatically tries different types of authentication.
The patch solves #76

Force to use specific authenticator

---

lib/agent/batch/Headers.js
lib/agent/batch/Response.js
test/unit/agent/batch/Headers.js
test/unit/agent/batch/Response.js

Function import implementation follows Fetch API
after new Fetch API usage, but Batch processing
does not emulate the Fetch APi. Patch implements
Response.json method and Headers class.
Topic: #77

[FIX] Emulate Fetch API response in batch processing

---

doc/INITIALIZE.md
lib/agent/Agent.js
lib/agent/authentication.js
lib/agent/authentication/cert.js
lib/agent/settings.js
test/unit/agent/Agent.js
test/unit/agent/authentication/cert.js
test/unit/agent/settings.js

The patch implement authentication via client ceriticates in PEM and PFX format. New parameters ca, cert, key, pfx and passphrase added to initialization. The client certificat authentication is not part of "automatic" determination of authentication type.
Topic: #81

[FEATURE] Add authentication by client certificate

---

.reuse/dep5
lib/engine/QueryableResource.js
lib/engine/RequestDefinition.js
lib/model/oasis/dataSource/EntitySet.js
lib/model/oasis/schema/Action.js
test/unit/engine/QueryableResource.js
test/unit/engine/RequestDefinition.js
test/unit/model/oasis/dataSource/EntitySet.js
test/unit/model/oasis/schema/Action.js

- [INTERNAL] Ignore TypeScript type definitons for licences
- [FIX] Use default entityTypePath in Action definition

fix/master/#96/Missing InBound actions

---

lib/engine/QueryableResource.js
test/unit/engine/QueryableResource.js

In case that service is using eTag it is necessary to have If-Match header otherwise MERGE requests throws an error

Add If-Match header to MERGE request
